#!/usr/bin/perl

# RCS information (required by Perl::Critic)
# enable substitution with:
#   $ svn propset svn:keywords "Id Revision HeadURL Source Date"
#
#   $Id$
#   $Revision$
#   $HeadURL$
#   $Date$

use 5.008;
use strict;
use warnings;
use Carp;

use version; our $VERSION = '1.0.0';

use Data::Dumper;
use File::Slurp;
use English qw(-no_match_vars);
use Getopt::Long;
use Pod::Usage qw(pod2usage);
use List::Util qw(first);

##############################################################################
# Configuration

Getopt::Long::Configure( 'bundling', 'ignorecase', );

##############################################################################
# Global vars

# Hash of hashes containing the checks to be perfomed
# - name        : name of the check
# - *           : anonymous hash with
#   - severity    : the severity level of the check
#   - function    : the subrouting implementing the test
#   - description : a short description
my %checks;

my $getopt_result;
my $help;
my $severity  = 1;
my $verbosity = 0;

# constants

my $GENTLE = 5;
my $STERN  = 4;
my $HARSH  = 3;
my $CRUEL  = 2;
my $BRUTAL = 1;

my $NAME_PATTERN = '[A-Za-z0-9_]+';

##############################################################################
# Subroutines

##############################################################################
# Usage     : verbose("some message string", $optional_verbosity_level);
# Purpose   : write a message if the verbosity level is high enough
# Returns   : n/a
# Arguments : message : message string
#             level   : options verbosity level
# Throws    : n/a
# Comments  : n/a
# See also  : n/a
sub verbose {

    # arguments
    my $message = shift;
    my $level   = shift;

    if ( !defined $level ) {
        $level = 0;
    }

    if ( $level < $verbosity ) {
        print $message;
    }

    return;

}

##############################################################################
# Usage     : perform_checks($filename)
# Purpose   : performs all the registered checks on the given filename
# Returns   : n/a
# Arguments : file : name of the file to check
# Throws    : n/a
# Comments  : n/a
# See also  : n/a
sub perform_checks {

    my $file = shift;

    verbose "checking $file\n";
    
    for my $name (keys %checks) {

        verbose '> checking rule: '
            . ${$checks{$name}}{description}
                . "\n", 1;
        
        &{${$checks{$name}}{function}}( $file, read_file($file) );
    }

    return;

}

##############################################################################
# Usage     : check_pattern($filename, $pattern, $message, @lines)
# Purpose   : searches for the given pattern in the lines array and prints a
#             message if found
# Returns   : n/a
# Arguments : $file    : name of the file to check
#             $pattern : the pattern to look for
#             $message : the warning message ('LINE_NUMBER' will be
#                        substituted with the current line number)
#             @lines   : array of lines of the given file
# Throws    : n/a
# Comments  : n/a
# See also  : n/a
sub check_pattern {

    my $file    = shift;
    my $pattern = shift;
    my $message = shift;
    my @lines   = @_;

    my $counter = 0;

    for my $line (@lines) {
        $counter++;
        if ( $line =~ /$pattern/mx ) {
            my $error = $message;
            $error =~ s/LINE_NUMBER/$counter/mx;
            print "$error\n";
        }
    }

    return;

}

##############################################################################
# Main

############################
# Parse command line options

Getopt::Long::Configure( 'bundling', 'no_ignore_case' );

$getopt_result = GetOptions(
    '1|brutal'   => sub { $severity = 1; },
    '2|cruel'    => sub { $severity = 2; },
    '3|harsh'    => sub { $severity = 3; },
    '4|stern'    => sub { $severity = 4; },
    '5|gentle'   => sub { $severity = 5; },
    'severity'   => \$severity,
    'help|h|?'   => \$help,
    'verbose|v+' => \$verbosity,
    'version|V'  => sub { print "bashcritic version $VERSION\n"; exit; },
) or pod2usage();

##############################
# Parse command line arguments

my @FILES = ();

if ( !@ARGV || ( @ARGV == 1 && $ARGV[0] eq q{-} ) ) {

    # Reading code from STDIN.  All the code is slurped into
    # a string.  PPI will barf if the string is just whitespace.
    my $code_string = do { local $RS = undef; <STDIN> };

    # Notice if STDIN was closed (pipe error, etc)
    if ( !defined $code_string ) {
        $code_string = q{};
    }

    $code_string =~ m{ \S+ }mx || confess qq{Nothing to critique.\n};
    @FILES = \$code_string;    #Convert to SCALAR ref for PPI
}
else {

    # Test to make sure all the specified files or directories
    # actually exist.  If any one of them is bogus, then die.
    if ( my $nonexistant = first { !-e $_ } @ARGV ) {
        my $msg = qq{No such file or directory: '$nonexistant'};
        pod2usage( -exitstatus => 1, -message => $msg, -verbose => 0 );
    }

    @FILES = @ARGV;
}

##############################################################################
# checks

# fill in names severities and descriptions first (functions
# will be inserted later so that they can use these fields in the
# definition

####################
# portability checks
#
# checks from rules described by http://www.bash-hackers.org/wiki/doku.php?id=scripting:nonportable

# SOURCE

$checks{SOURCE} = {
    severity    => $STERN,
    description => '"source FILE" is not portable use ". FILE" instead',
};
$checks{SOURCE}{function} = sub {
    my $file = shift;
    check_pattern(
        $file,
        'source\ ',
        "Severity $checks{SOURCE}{severity} at $file:LINE_NUMBER: " . $checks{SOURCE}{description},
        @_,
    );
};        

# DECLARE

$checks{DECLARE} = {
    severity    => $STERN,
    description => '"declare keyword" is not portable use "typeset keyword" to define local variables '
        . '(or variables with special attributes)',
};
$checks{DECLARE}{function} = sub {
    my $file = shift;
    check_pattern(
        $file,
        'declare\ ',
        "Severity $checks{DECLARE}{severity} at $file:LINE_NUMBER: " . $checks{DECLARE}{description},
        @_,
    );
};

# HERE_STRING
$checks{HERE_STRING} = {
    severity    => $STERN,
    description => 'Avoid here-strings (a special form of the here-document) in portable scripts',
};
$checks{HERE_STRING}{function} = sub {
    my $file = shift;
    check_pattern(
        $file,
        '<<<',
        "Severity $checks{HERE_STRING}{severity} at $file:LINE_NUMBER: " . $checks{HERE_STRING}{description},
        @_,
    );
};

# EXPORT_ASSIGN
$checks{EXPORT_ASSIGN} = {
    severity    => $STERN,
    description => 'Though POSIX allows it, many shells don’t want the assignment and the exporting in one command',
};
$checks{EXPORT_ASSIGN}{function} = sub {
    my $file = shift;
    check_pattern(
        $file,
        'export\ .*=',
        "Severity $checks{EXPORT_ASSIGN}{severity} at $file:LINE_NUMBER: " . $checks{EXPORT_ASSIGN}{description},
        @_,
    );
};

#
#    # arithmetic compunds
#    sub {
#        my $file = shift;
#        check_pattern(
#            $file,
#            '^[^:]*\(\(.*\)\)',
#            "Severity $STERN at $file:LINE_NUMBER: "
#              . 'POSIX does’t define an arithmetic compund command, many shells don’t know it. Using the pseudo-command : and the arithmetic expansion $(( )) is a kind of workaround here.',
#            @_,
#        );
#    },
#
#    # Bashish test keyword
#    sub {
#        my $file = shift;
#        check_pattern(
#            $file,
#            '\[\[\ .*\ \]\]',
#            "Severity $STERN at $file:LINE_NUMBER: "
#              . 'The Bashish test keyword "[[" is reserved by POSIX®, but not defined. Use the old fashioned way with the test command ("test" or "[").',
#            @_,
#        );
#    },
#
#    #####################
#    # obsolete constructs
#    #
#    # http://www.bash-hackers.org/wiki/doku.php?id=scripting:obsolete
#
#    # c-shell redirection
#    sub {
#        my $file = shift;
#        check_pattern(
#            $file,
#            '(&>)|(>&)',
#            "Severity $STERN at $file:LINE_NUMBER: "
#              . 'The &>FILE >&FILE redirection syntax is short for >FILE 2>&1 and is derived from the C-Shell. It’s very old and not part of POSIX',
#            @_,
#        );
#    },
#
#    # $[ EXPRESSION ]
#    sub {
#        my $file = shift;
#        check_pattern(
#            $file,
#            '\$\[.*\]',
#            "Severity $STERN at $file:LINE_NUMBER: "
#              . 'The $[EXPRESSION] syntax is completely replaced by the POSIX-conform arithmetic expansion $((EXPRESSION))'
#              . @_,
#        );
#    },
#
#    # ` COMMAND `
#    sub {
#        my $file = shift;
#        check_pattern(
#            $file,
#            '\`.*\`',
#            "Severity $HARSH at $file:LINE_NUMBER: "
#              . '`COMMANDS` is an older form of the command substitution. The usage of the POSIX-form $(COMMANDS) is preferred.',
#            @_,
#        );
#    },
#
#    # function keyword
#    sub {
#        my $file = shift;
#        check_pattern(
#            $file,
#            'function\ *' . $NAME_PATTERN . '\ *{',
#            "Severity $STERN at $file:LINE_NUMBER: "
#              . 'The "function NAME { ...; }" form of the function definition is not recommended simply use NAME() { ...; } to define a function.',
#            @_,
#        );
#    },
#
#    # let EXPRESSION
#    sub {
#        my $file = shift;
#        check_pattern(
#            $file,
#            'let\ ',
#            "Severity $HARSH at $file:LINE_NUMBER: "
#              . '"let MATH" is the classic form of the arithmetic evaluation command. Bash has an own compound command for that, which should be used if possible: ": $((MATH))."',
#            @_,
#        );
#    },
#
#    ############
#    # Formatting
#
#    # lines too long
#    sub {
#        my $file    = shift;
#        my @lines   = read_file($file);
#        my $counter = 0;
#        for my $line (@lines) {
#            $counter++;
#            if ( length $line > 78 ) {
#                print "Severity $CRUEL at $file:$counter: "
#                  . "line is longer than 78 characters, consider splitting it over multiple lines to increase readability.\n";
#            }
#        }
#    },

for my $file (@FILES) {
    perform_checks($file);
}

1;

__END__

=pod

=head1 NAME

C<bashcritic> - critiques shell scripts

=head1 SYNOPSIS

  bashcritic [-12345 | -brutal | -cruel | -harsh | -stern | -gentle]
             [-severity number | name]
             [-verbose ]
             {FILE | STDIN}

=head1 DESCRIPTION

critiques shell scripts

=head1 VERSION

Version 1.0.0

=head1 REQUIRED ARGUMENTS

none

=head1 OPTIONS

=head1 USAGE EXAMPLES

bashcritic -gentle file_to_analyze

=head1 DIAGNOSTICS

=head1 EXIT STATUS

1 on error, 0 otherwise

=head1 DEPENDENCIES

bashcritic depends on

=over 4

=item * Carp;

=item * version;

=item * English

=item * Getopt::Long

=back

=head1 CONFIGURATION

=head1 INCOMPATIBILITIES

None reported.

=head1 SEE ALSO

=head1 BUGS AND LIMITATIONS

No bugs have been reported.

Please report any bugs or feature requests to matteo.corti@id.ethz.ch,
or through the web interface at
https://trac.id.ethz.ch/projects/bashcritic

=head1 AUTHOR

Matteo Corti <matteo.corti@id.ethz.ch>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2007, ETH Zurich.

This module is free software; you can redistribute it and/or modify it
under the terms of GNU general public license (gpl) version 3.
See the LICENSE file for details.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT
WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER
PARTIES PROVIDE THE SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
SOFTWARE IS WITH YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME
THE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE LIABLE
TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL, OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A
FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF
SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
DAMAGES.

=head1 ACKNOWLEDGMENTS

