---
abstract: ~
author:
  - 'Matteo Corti <matteo.corti@id.ethz.ch>'
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: bashcritic
no_index:
  directory:
    - inc
requires:
  Data::Dumper: 0
  English: 0
  File::Slurp: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  List::Util: 0
  Pod::Usage: 0
  perl: 5.8.0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.3.3
